# Generated by Django 5.0 on 2023-12-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricette', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='id',
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='codice',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
