# Generated by Django 5.0 on 2023-12-29 23:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricette', '0002_remove_ingrediente_id_alter_ingrediente_codice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ricetta',
            fields=[
                ('codice', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descrizione', models.CharField(max_length=200)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='data_aggiornamento',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='data_creazione',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Miscela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosaggio', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ricette.ingrediente')),
                ('ricetta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ricette.ricetta')),
            ],
        ),
    ]
